apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: bookstore
type: Opaque
stringData:
  mongo-uri: mongodb+srv://sangeethagowda944_db_user:JIWiojy4TreaWSwa@cluster0.b1ogb9f.mongodb.net/bookstore?appName=Cluster0/
